/** Copyright ©2025 Devexperts LLC.
All rights reserved. Any unauthorized use will constitute an infringement of copyright.
In case of any questions regarding types of use, please contact legal@devexperts.com.
This notice must remain intact.
**/
/**
 * @doc-tags e2e
 */
export declare const TEST_IDS: {
    suggest_main: string;
    suggest_compare: string;
    selectbox_period_anchor: string;
    selectbox_period_popover: string;
    selectbox_chart_type_anchor: string;
    selectbox_chart_type_popover: string;
    selectbox_chart_drawings_anchor: string;
    selectbox_chart_drawings_popover: string;
    button_studies: string;
    popup_studies: string;
    popup_studies_footer_close: string;
    popup_studies_add_script_button: string;
    dxscript_popup: string;
    dxscript_popup_editable_input: string;
    dxscript_popup_button_close: string;
    dxscript_popup_button_add_to_chart: string;
    dxscript_popup_button_update: string;
    button_compare: string;
    multichart_container: string;
    multichart_button: string;
    multichart_popover: string;
    multichart_layouts: string;
    multichart_sync_options: string;
    indicator_template_button: string;
    indicator_template_placeholder: string;
    indicator_template_input: string;
    indicator_template_input_button: string;
    indicator_template_input_error: string;
    indicator_template_input_wrapper: string;
    chart_footer: string;
    chart_main_area: string;
    chart_layout_button: string;
    chart_layout_placeholder: string;
    chart_layout_input: string;
    chart_layout_input_button: string;
    chart_layout_input_error: string;
    chart_layout_input_wrapper: string;
    custom_period_input: string;
    custom_period_placeholder: string;
    custom_period_input_error: string;
    custom_period_input_wrapper: string;
    custom_period_input_button: string;
    chart_layers_button: string;
    snapshot_sharing_button: string;
    snapshot_sharing_item: string;
    settings_popup_button: string;
    settings_popup_close_button: string;
    settings_popup_session_breaks_field: string;
    settings_popup_extended_hours_field: string;
    sidebar_toggle_button: string;
    sidebar_footer_button: string;
    switch_axis_type_button: string;
    zoom_button_in: string;
    zoom_button_out: string;
    multi_chart_template: string;
    time_zone_component: string;
    time_zone_dropdown_item: string;
    time_zone_search: string;
    sidebar_drawing_container: string;
    sidebar_drawing_item: string;
    snapshot_menu: string;
    chart_settings_button: string;
    chart_settings_checkbox: string;
    chart_settings_color_button: string;
    chart_settings_color_pallete_button: string;
    chart_settings: string;
    chart_settings_tabs: string;
    chart_settings_tab_general: string;
    chart_settings_tab_market: string;
    chart_settings_tab_colors: string;
    chart_settings_tab_legend: string;
    chart_settings_tab_scales: string;
    chart_settings_tab_general_content: string;
    chart_settings_tab_market_content: string;
    chart_settings_tab_colors_content: string;
    chart_settings_tab_scales_content: string;
    drawing_groups_dropdown: string;
    drawing_groups_anchor: string;
    drawing_groups_input: string;
    drawing_groups_input_error: string;
    drawing_groups_input_wrapper: string;
    drawing_groups_input_button: string;
    drawing_groups_placeholder: string;
    drawings_sidebar: string;
    drawing_settings_draggble_bar: string;
    drawing_settings_popup: string;
    drawing_settings_button: string;
    chart_aggregation_period_dropdown_item: string;
    chart_type_dropdown_item: string;
    chart_drawings_dropdown_item: string;
    chart_drawings_dropdown_visibility: string;
    chart_drawings_dropdown_clear: string;
    chart_legend_secondary_series_item: string;
    indicator_item_left: string;
    indicator_item_right: string;
    indicator_template_menu_item: string;
    indicator_added_studies_list: string;
    chart_layout_menu_item: string;
    chart_react_wrapper: string;
    order_entry_add_button: string;
    order_entry_close_button: string;
    order_entry_buy_button: string;
    order_entry_sell_button: string;
    order_item: string;
    protection_order_item: string;
    position_item: string;
};
export type TESTID = typeof TEST_IDS;
